controllers/ManagerController.php
<?php

namespace app\controllers;

use app\models\db\User;

class ManagerController extends Base
{
    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        if (in_array($action->id, ['siteconfig'])) {
            // No cookieValidationKey is set in the beginning
            \Yii::$app->request->enableCookieValidation = false;
            return parent::beforeAction($action);
        }

        if (!$this->getParams()->multisiteMode && !in_array($action->id, ['siteconfig', 'userlist'])) {
            return false;
        }

        $currentHost = parse_url(\Yii::$app->request->getAbsoluteUrl(), PHP_URL_HOST);
        $managerHost = parse_url($this->getParams()->domainPlain, PHP_URL_HOST);
        if ($currentHost !== $managerHost) {
            return $this->redirect($this->getParams()->domainPlain, 301);
        }

        return parent::beforeAction($action);
    }

    /**
     * @return string
     * @throws \yii\base\ExitException
     */
    public function actionSiteconfig()
    {
        if (!User::currentUserIsSuperuser()) {
            return $this->showErrorpage(403, 'Only admins are allowed to access this page.');
        }

        $configfile = dirname(__DIR__) . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR . 'config.json';
        $config     = $this->getParams();

        if ($config->multisiteMode) {
            return $this->showErrorpage(500, 'This configuration tool can only be used for single-site installations.');
        }

        $post = \Yii::$app->request->post();
        if (isset($post['save'])) {
            $config->resourceBase          = $post['resourceBase'];
            $config->baseLanguage          = $post['baseLanguage'];
            $config->lualatexPath          = $post['lualatexPath'];
            $config->mailFromEmail         = $post['mailFromEmail'];
            $config->mailFromName          = $post['mailFromName'];
            $config->confirmEmailAddresses = isset($post['confirmEmailAddresses']);

            switch ($post['mailService']['transport']) {
                case 'none':
                    $config->mailService = ['transport' => 'none'];
                    break;
                case 'sendmail':
                    $config->mailService = ['transport' => 'sendmail'];
                    break;
                case 'mandrill':
                    $config->mailService = [
                        'transport' => 'mandrill',
                        'apiKey'    => $post['mailService']['mandrillApiKey'],
                    ];
                    break;
                case 'mailgun':
                    $config->mailService = [
                        'transport' => 'mailgun',
                        'apiKey'    => $post['mailService']['mailgunApiKey'],
                        'domain'    => $post['mailService']['mailgunDomain'],
                    ];
                    break;
                case 'mailjet':
                    $config->mailService = [
                        'transport'        => 'mailjet',
                        'apiKey'           => $post['mailService']['mailjetApiKey'],
                        'mailjetApiSecret' => $post['mailService']['mailjetApiSecret'],
                    ];
                    break;
                case 'smtp':
                    $config->mailService = [
                        'transport' => 'smtp',
                        'host'      => $post['mailService']['smtpHost'],
                        'port'      => $post['mailService']['smtpPort'],
                        'authType'  => $post['mailService']['smtpAuthType'],
                    ];
                    if ($post['mailService']['smtpAuthType'] != 'none') {
                        $config->mailService['username'] = $post['mailService']['smtpUsername'];
                        $config->mailService['password'] = $post['mailService']['smtpPassword'];
                    }
                    break;
            }

            $file = fopen($configfile, 'w');
            fwrite($file, json_encode($config, JSON_PRETTY_PRINT));
            fclose($file);

            \yii::$app->session->setFlash('success', \Yii::t('manager', 'saved'));
        }

        $editable = is_writable($configfile);

        if (function_exists('posix_getpwuid') && function_exists('posix_geteuid')) {
            $myUsername         = posix_getpwuid(posix_geteuid());
            $makeEditabeCommand = 'sudo chown ' . $myUsername['name'] . ' ' . $configfile;
        } else {
            $makeEditabeCommand = 'not available';
        }

        return $this->render('siteconfig', [
            'config'             => $config,
            'editable'           => $editable,
            'makeEditabeCommand' => $makeEditabeCommand,
        ]);
    }

    /**
     * @return string
     * @throws \yii\base\ExitException
     */
    public function actionUserlist()
    {
        if (!User::currentUserIsSuperuser()) {
            return $this->showErrorpage(403, 'Only admins are allowed to access this page.');
        }

        if ($this->isPostSet('deleteUser')) {
            $user = User::findOne(['id' => \Yii::$app->request->post('deleteUser')]);
            if ($user) {
                $user->deleteAccount();
                \Yii::$app->session->setFlash('success', \Yii::t('admin', 'siteacc_user_del_done'));
            }
        }

        $users = User::find()->where('status != ' . IntVal(User::STATUS_DELETED))->orderBy('dateCreation DESC')->all();

        return $this->render('userlist', ['users' => $users]);
    }
}

views/admin/index/_site_access_accounts.php
<?php

use app\models\db\Consultation;
use app\models\db\ConsultationUserPrivilege;
use yii\helpers\Html;

/**
 * @var \app\controllers\Base $controller
 * @var Consultation $consultation
 */

echo '<section class="showManagedUsers hidden">';

echo '<h2 class="green">' . Yii::t('admin', 'siteacc_accounts_title') . '</h2>';


$preEmails    = '';
$preNames     = '';
$prePasswords = '';
$preSamlWW    = '';
$preText      = Yii::t('admin', 'siteacc_email_text_pre');
$hasEmail     = ($controller->getParams()->mailService['transport'] !== 'none');
$hasSaml      = $controller->getParams()->isSamlActive();

echo $controller->showErrors();


/** @var ConsultationUserPrivilege[] $privilegesWithAccess */
$privilegesWithAccess = [];
/** @var ConsultationUserPrivilege[] $privilegesScreening */
$privilegesScreening  = [];
foreach ($consultation->userPrivileges as $priv) {
    if (!$priv->user) {
        continue;
    }
    if ($priv->isAskingForPermission()) {
        $privilegesScreening[] = $priv;
    } else {
        $privilegesWithAccess[] = $priv;
    }
}

if (count($privilegesWithAccess) > 0) {
    ?>
    <?= Html::beginForm('', 'post', ['id' => 'accountsEditForm', 'class' => 'adminForm form-horizontal content']) ?>
    <table class="accountListTable table table-condensed">
        <thead>
        <tr>
            <th class="nameCol"><?= Yii::t('admin', 'siteacc_user_name') ?></th>
            <th class="emailCol"><?= Yii::t('admin', 'siteacc_user_login') ?></th>
            <th class="accessViewCol"><?= Yii::t('admin', 'siteacc_user_read') ?></th>
            <th class="accessCreateCol"><?= Yii::t('admin', 'siteacc_user_write') ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($privilegesWithAccess as $privilege) {
            $checkView   = ($privilege->privilegeView === 1 ? 'checked' : '');
            $checkCreate = ($privilege->privilegeCreate === 1 ? 'checked' : '');
            $user        = $privilege->user;
            ?>
            <tr class="user<?= $user->id ?>">
                <td class="nameCol"><?= Html::encode($user->name) ?></td>
                <td class="emailCol"><?= Html::encode($user->getAuthName()) ?></td>
                <td class="accessViewCol">
                    <label>
                        <span class="sr-only"><?= Yii::t('admin', 'siteacc_perm_read') ?></span>
                        <input type="checkbox" name="access[<?= $user->id ?>][]"
                               value="view" <?= $checkView ?>>
                    </label>
                </td>
                <td class="accessCreateCol">
                    <label>
                        <span class="sr-only"><?= Yii::t('admin', 'siteacc_perm_write') ?></span>
                        <input type="checkbox" name="access[<?= $user->id ?>][]"
                               value="create" <?= $checkCreate ?>>
                    </label>
                </td>
                <td class="deleteCol">
                    <?php
                    if ($user->id !== \app\models\db\User::getCurrentUser()->id) {
                        ?>
                        <button type="button" data-id="<?= $user->id ?>" class="link deleteUser"
                                data-name="<?= Html::encode($user->name . ' / ' . $user->getAuthName()) ?>"
                                title="<?= Yii::t('admin', 'siteacc_del_btn') ?>">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            <span class="sr-only"><?= Yii::t('admin', 'siteacc_del_btn') ?></span>
                        </button>
                        <?php
                    }
                    ?>
                </td>
            </tr>
            <?php
        }
        ?>
        </tbody>
    </table>

    <div class="saveholder">
        <button type="submit" name="saveUsers" class="btn btn-primary"><?= Yii::t('base', 'save') ?></button>
    </div>
    <?php
    echo Html::endForm();
}

if (count($privilegesScreening) > 0) {
    ?>
    <h3 class="lightgreen"><?= Yii::t('admin', 'siteacc_screen_users') ?></h3>
    <?= Html::beginForm('', 'post', ['id' => 'accountsScreenForm', 'class' => 'adminForm form-horizontal content']) ?>
    <table class="accountListTable table table-condensed">
        <thead>
        <tr>
            <th class="screenCol"></th>
            <th class="nameCol"><?= Yii::t('admin', 'siteacc_user_name') ?></th>
            <th class="emailCol"><?= Yii::t('admin', 'siteacc_user_login') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($privilegesScreening as $privilege) {
            $user        = $privilege->user;
            ?>
            <tr class="user<?= $user->id ?>">
                <td class="selectCol">
                    <input type="checkbox" name="userId[]" value="<?= $user->id ?>" id="screenUser<?= $user->id ?>">
                </td>
                <td class="nameCol">
                    <label for="screenUser<?= $user->id ?>"><?= Html::encode($user->name) ?></label>
                </td>
                <td class="emailCol">
                    <label for="screenUser<?= $user->id ?>"><?= Html::encode($user->getAuthName()) ?></label>
                </td>
            </tr>
            <?php
        }
        ?>
        </tbody>
    </table>

    <div class="saveholder">
        <button type="submit" name="noAccess" class="btn btn-danger">
            <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
            <?= Yii::t('admin', 'siteacc_noscreen_users_btn') ?>
        </button>
        <button type="submit" name="grantAccess" class="btn btn-success">
            <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            <?= Yii::t('admin', 'siteacc_screen_users_btn') ?>
        </button>
    </div>
    <?php
    echo Html::endForm();
}


echo Html::beginForm('', 'post', ['id' => 'accountsCreateForm', 'class' => 'adminForm form-horizontal']);
?>
    <h3 class="lightgreen"><?= Yii::t('admin', 'siteacc_new_users') ?></h3>
    <div class="addUserTypeChooser content">
        <button class="btn btn-default addUsersOpener email" type="button" data-type="email">
            <?= Yii::t('admin', 'siteacc_add_email_btn') ?>
        </button>
        <?php
        if ($hasSaml) {
            ?>
            <button class="btn btn-default addUsersOpener samlWW" type="button" data-type="samlWW">
                <?= Yii::t('admin', 'siteacc_add_ww_btn') ?>
            </button>
            <?php
        }
        ?>
    </div>
<?php

if ($hasSaml) {
    ?>
    <section class="addUsersByLogin samlWW hidden content">
        <div class="row">
            <label class="col-md-4 col-md-offset-4">
                <?= Yii::t('admin', 'siteacc_new_saml_ww') ?>
                <textarea id="samlWW" name="samlWW" rows="15"><?= Html::encode($preSamlWW) ?></textarea>
            </label>
        </div>

        <br><br>
        <div class="saveholder">
            <button type="submit" name="addUsers" class="btn btn-primary">
                <?= Yii::t('admin', 'siteacc_new_do') ?>
            </button>
        </div>
    </section>
    <?php
}


if ($hasEmail) {
    ?>
    <section class="addUsersByLogin email hidden content">
        <div class="accountEditExplanation alert alert-info">
            <?= Yii::t('admin', 'siteacc_acc_expl_mail') ?>
        </div>
        <div class="row">
            <label class="col-md-6">
                <?= Yii::t('admin', 'siteacc_new_emails') ?>
                <textarea id="emailAddresses" name="emailAddresses" rows="15"><?= Html::encode($preEmails) ?></textarea>
            </label>

            <label class="col-md-6">
                <?= Yii::t('admin', 'siteacc_new_names') ?>
                <textarea id="names" name="names" rows="15"><?= Html::encode($preNames) ?></textarea>
            </label>
        </div>

        <label for="emailText"><?= Yii::t('admin', 'siteacc_new_text') ?>:</label>
        <textarea id="emailText" name="emailText" rows="15" cols="80"><?= Html::encode($preText) ?></textarea>

        <br><br>
        <div class="saveholder">
            <button type="submit" name="addUsers" class="btn btn-primary">
                <?= Yii::t('admin', 'siteacc_new_do') ?>
            </button>
        </div>
    </section>
    <?php
} else {
    ?>
    <section class="addUsersByLogin email hidden content">
        <div class="accountEditExplanation alert alert-info">
            <?= Yii::t('admin', 'siteacc_acc_expl_nomail') ?>
        </div>
        <div class="row">
            <label class="col-md-4">
                <?= Yii::t('admin', 'siteacc_new_emails') ?>
                <textarea id="emailAddresses" name="emailAddresses" rows="15"><?= Html::encode($preEmails) ?></textarea>
            </label>

            <label class="col-md-4">
                <?= Yii::t('admin', 'siteacc_new_pass') ?>
                <textarea id="passwords" name="passwords" rows="15"><?= Html::encode($prePasswords) ?></textarea>
            </label>

            <label class="col-md-4"><?= Yii::t('admin', 'siteacc_new_names') ?>
                <textarea id="names" name="names" rows="15"><?= Html::encode($preNames) ?></textarea>
            </label>
        </div>
        <br><br>
        <div class="saveholder">
            <button type="submit" name="addUsers" class="btn btn-primary">
                <?= Yii::t('admin', 'siteacc_new_do') ?>
            </button>
        </div>
    </section>
    <?php
}

echo Html::endForm();


echo '</section>';

views/admin/index/_site_access_admins.php
<?php

use app\components\HTMLTools;
use app\models\db\User;
use yii\helpers\Html;

/**
 * @var array $admins
 */
$hasProposedProcedures = $controller->consultation->hasProposedProcedures();

?>
<div class="adminForm form-horizontal">
    <h2 class="green"><?= Yii::t('admin', 'siteacc_admins_title') ?></h2>
    <section class="content">
        <?php
        echo Html::beginForm('', 'post', ['id' => 'adminForm', 'class' => 'adminForm form-horizontal siteaccAdminsForm']);

        $myself = User::getCurrentUser();

        foreach ($admins as $admin) {
            $types = $admin['types'];
            /** @var User $user */
            $user = $admin['user'];

            $isMe = ($user->id === User::getCurrentUser()->id);
            ?>
            <section class="adminCard admin<?= $user->id ?>">
                <header>
                    <?php
                    if (!$isMe) { ?>
                        <button class="link removeAdmin removeAdmin<?= $user->id ?>"
                                type="button" data-id="<?= $user->id ?>"
                                title="<?= Yii::t('admin', 'siteacc_admins_del') ?>">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            <span class="sr-only"><?= Yii::t('admin', 'siteacc_admins_del') ?></span>
                        </button>
                        <?php
                    }

                    echo '<span class="name">';
                    echo Html::encode($user->getAuthName());
                    if ($user->name !== '') {
                        echo ' (' . Html::encode($user->name) . ')';
                    }
                    echo '</span>';
                    ?>
                </header>
                <main>
                    <label class="type typeSite">
                        <input type="checkbox" name="adminTypes[<?= $user->id ?>][]" value="site"
                            <?= (in_array('site', $types) ? 'checked' : '') ?>
                            <?= ($isMe ? 'disabled' : '') ?>>
                        <?= Yii::t('admin', 'siteacc_admins_all_cons') ?>
                    </label>
                    <label class="type typeCon">
                        <input type="checkbox" name="adminTypes[<?= $user->id ?>][]" value="consultation"
                            <?= (in_array('consultation', $types) ? 'checked' : '') ?>
                            <?= ($isMe ? 'disabled' : '') ?>>
                        <?= Yii::t('admin', 'siteacc_admins_one_con') ?>
                    </label>
                    <label class="type typeProposal">
                        <input type="checkbox" name="adminTypes[<?= $user->id ?>][]" value="proposal"
                            <?= (in_array('proposal', $types) ? 'checked' : '') ?>
                            <?= ($isMe ? 'disabled' : '') ?>>
                        <?= Yii::t('admin', 'siteacc_admins_proposals') ?>
                    </label>
                    <?php
                    if ($hasProposedProcedures) {
                        if ($user->getSettingsObj()->ppReplyTo === '') {
                            ?>
                            <button class="btn btn-link pull-right ppReplyToOpener" type="button"
                                    title="<?= Html::encode(Yii::t('admin', 'siteacc_admins_pp_replyto')) ?>">
                                @
                            </button>
                            <?php
                        }
                        ?>
                        <div class="ppReplyTo row <?= ($user->getSettingsObj()->ppReplyTo === '' ? 'hidden' : '') ?>">
                            <label class="col-md-6 control-label" for="ppReplyTo<?= $user->id ?>">
                                <?= Yii::t('admin', 'siteacc_admins_pp_replyto') ?>:
                            </label>
                            <div class="col-md-5">
                                <input class="form-control" id="ppReplyTo<?= $user->id ?>" name="ppReplyTo[<?= $user->id ?>]"
                                       value="<?= Html::encode($user->getSettingsObj()->ppReplyTo) ?>">
                            </div>
                        </div>
                        <?php
                    }
                    ?>
                </main>
            </section>
            <?php
        }
        ?>
        <div class="saveRow">
            <button type="submit" name="saveAdmin" class="btn btn-primary"><?= Yii::t('base', 'save') ?></button>
        </div>
        <?php
        echo Html::endForm();
        ?>

        <br>

        <?php
        echo Html::beginForm('', 'post', ['id' => 'adminAddForm', 'class' => 'adminForm form-horizontal']);
        ?>
        <h4><?= Yii::t('admin', 'siteacc_admins_add') ?></h4>
        <div class="row">
            <div class="col-md-3 admin-type">
                <?= HTMLTools::fueluxSelectbox('addType', [
                    'wurzelwerk' => Yii::t('admin', 'siteacc_add_ww') . ':',
                    'email'      => Yii::t('admin', 'siteacc_add_email') . ':',
                ]) ?>
            </div>
            <div class="col-md-4">
                <input type="text" name="addUsername" value="" id="addUsername" class="form-control"
                       title="<?= Html::encode(Yii::t('admin', 'siteacc_add_name_title')) ?>"
                       placeholder="<?= Html::encode(Yii::t('admin', 'siteacc_add_name_place')) ?>" required>
            </div>
            <div class="col-md-3">
                <button type="submit" name="addAdmin"
                        class="btn btn-primary"><?= Yii::t('admin', 'siteacc_add_btn') ?></button>
            </div>
        </div>
        <?php
        echo Html::endForm();
        ?>
        <br><br>
    </section>
</div>

views/admin/index/index.php
<?php

use app\components\updater\UpdateChecker;
use app\components\UrlHelper;
use app\models\db\User;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var \app\models\AdminTodoItem[] $todo
 * @var \app\models\db\Site $site
 * @var \app\models\db\Consultation $consultation
 */

/** @var \app\controllers\Base $controller */
$controller = $this->context;
$layout     = $controller->layoutParams;

$this->title = Yii::t('admin', 'index_title');
$layout->addCSS('css/backend.css');
$layout->addBreadcrumb(Yii::t('admin', 'bread_settings'));
$layout->addAMDModule('backend/AdminIndex');

echo '<h1>' . Yii::t('admin', 'index_settings') . '</h1>';


echo $controller->showErrors();

echo '<div class="content adminIndex"><div class="adminIndexHolder"><div>';

echo '<ul class="adminMenuList"><li>';

echo Html::a(
    Yii::t('admin', 'index_consultation_settings'),
    UrlHelper::createUrl('admin/index/consultation'),
    ['id' => 'consultationLink']
);

echo '</li><li class="secondary">';
echo Html::a(
    Yii::t('admin', 'index_appearance'),
    UrlHelper::createUrl('admin/index/appearance'),
    ['id' => 'appearanceLink']
);

echo '</li><li class="secondary">';
echo Html::a(
    Yii::t('admin', 'Translation / Wording'),
    UrlHelper::createUrl('admin/index/translation'),
    ['id' => 'translationLink']
);
echo '</li>';

echo '<li class="secondary">';
echo Html::a(
    Yii::t('admin', 'index_pages'),
    UrlHelper::createUrl('pages/list-pages'),
    ['id' => 'contentPages']
);
echo '</li>';

echo '<li>' . Yii::t('admin', 'index_motion_types') . '<ul>';
foreach ($consultation->motionTypes as $motionType) {
    echo '<li>';
    $sectionsUrl = UrlHelper::createUrl(['admin/motion/type', 'motionTypeId' => $motionType->id]);
    echo Html::a(Html::encode($motionType->titlePlural), $sectionsUrl, ['class' => 'motionType' . $motionType->id]);
    echo '</li>';
}
echo '<li class="secondary motionTypeCreate">';
echo Html::a(Yii::t('admin', 'motion_type_create_caller'), UrlHelper::createUrl(['admin/motion/typecreate']));
echo '</li>';
echo '</ul></li>';

if (User::havePrivilege($consultation, User::PRIVILEGE_SITE_ADMIN)) {
    echo '<li>';
    echo Html::a(
        Yii::t('admin', 'index_site_access'),
        UrlHelper::createUrl('admin/index/siteaccess'),
        ['class' => 'siteAccessLink']
    );
    echo '</li>';

    echo '<li>';
    echo Html::a(
        Yii::t('admin', 'index_site_consultations'),
        UrlHelper::createUrl('admin/index/siteconsultations'),
        ['class' => 'siteConsultationsLink']
    );
    echo '</li>';
}

if (User::currentUserIsSuperuser() && !$controller->getParams()->multisiteMode) {
    echo '<li>';
    echo Html::a(
        Yii::t('admin', 'index_site_user_list'),
        UrlHelper::createUrl('/manager/userlist'),
        ['class' => 'siteUserList']
    );
    echo '</li>';

    echo '<li>';
    echo Html::a(
        Yii::t('admin', 'index_site_config'),
        UrlHelper::createUrl('/manager/siteconfig'),
        ['class' => 'siteConfigLink']
    );
    echo '</li>';
}

echo '</ul>';
echo '</div><aside class="adminIndexSecondary">';

echo \app\models\layoutHooks\Layout::getAdminIndexHint($consultation);

if (User::currentUserIsSuperuser()) {
    if (UpdateChecker::isUpdaterAvailable()) {
        $url = UrlHelper::createUrl('admin/index/check-updates');
        echo '<article class="adminCard adminCardUpdates">';
        echo '<header><h2>' . Yii::t('admin', 'updates_title') . '</h2></header>';
        echo '<main data-src="' . Html::encode($url) . '">';
        echo Yii::t('admin', 'updates_loading');
        echo '</main></article>';
    }

    if (version_compare(PHP_VERSION, ANTRAGSGRUEN_NEXT_PHP_VERSION, '<')) {
        echo '<article class="adminCard">';
        echo '<header><h2>' . Yii::t('admin', 'php_version_hint_title') . '</h2></header>';
        echo '<main>';
        echo str_replace('%CURR%', PHP_VERSION, Yii::t('admin', 'php_version_hint_text'));
        echo '</main></article>';
    }

    echo Html::beginForm('', 'post', ['class' => 'sysadminForm']);
    echo '<button type="submit" name="flushCaches" class="btn btn-small btn-default">' .
         Yii::t('admin', 'index_flush_caches') . '</button>';
    echo Html::endForm();
}


echo '</aside></div>';

if (User::havePrivilege($consultation, User::PRIVILEGE_CONSULTATION_SETTINGS)) {
    if (count($site->consultations) === 1) {
        echo Html::beginForm('', 'post', ['class' => 'delSiteCaller']);
        echo '<button class="btn-link" type="submit" name="delSite">' .
             '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> ' . Yii::t('admin', 'index_site_del') .
             '</button>';
        echo Html::endForm();
    }
}

echo '</div>';

views/admin/index/index_updates.php
<?php

use app\components\UrlHelper;
use yii\helpers\Html;

try {
    $updates = \app\components\updater\UpdateChecker::getAvailableUpdates();
    $migrations = \app\components\updater\MigrateHelper::getAvailableMigrations();
    if (count($updates) === 0 && count($migrations) === 0) {
        echo \Yii::t('admin', 'updates_none');
    } else {
        echo '<ul>';
        foreach ($updates as $update) {
            echo '<li>' . Html::encode($update->version);
            echo ' <button class="showChanges btn-link">' . \Yii::t('admin', 'updates_show_changes') . '</button>';
            echo '<div class="changes hidden">' . nl2br(Html::encode($update->changelog)) . '</div>';
            echo '</li>';
        }
        echo '</ul>';

        if (count($migrations) > 0) {
            echo '<div>' . \Yii::t('admin', 'updates_migrate') . '</div>';
        }

        echo Html::beginForm(UrlHelper::createUrl('admin/index/goto-update'), 'post', ['class' => 'updateForm']);
        echo '<button type="submit" name="flushCaches" class="btn btn-small btn-success">' .
            \Yii::t('admin', 'updates_start') . '</button>';
        echo Html::endForm();
    }
} catch (\Exception $e) {
    echo \Yii::t('admin', 'updates_error');
}

views/admin/index/openslides2_user_list.php
<?php

use app\models\db\ISupporter;

/**
 * @var \yii\web\View $this
 * @var ISupporter[] $users
 */

/** @var \app\controllers\Base $controller */
$controller = $this->context;


$data          = [];
$usedUsernames = [];
foreach ($users as $user) {
    $userData   = [];
    $userData[] = ''; // Title
    if ($user->personType == ISupporter::PERSON_ORGANIZATION) {
        if (in_array($user->organization, $usedUsernames)) {
            continue;
        } else {
            $usedUsernames[] = $user->organization;
        }
        $userData[] = $user->organization;
        $userData[] = '';
    } else {
        if (in_array($user->name, $usedUsernames)) {
            continue;
        } else {
            $usedUsernames[] = $user->name;
        }
        $parts      = explode(' ', $user->name);
        $userData[] = array_shift($parts);
        $userData[] = implode(' ', $parts);
    }
    if ($user->personType == ISupporter::PERSON_ORGANIZATION) {
        $userData[] = ''; // Structure Level
    } else {
        $userData[] = $user->organization; // Structure Level
    }
    $userData[] = 0; // Group
    $userData[] = ''; // Comment
    $userData[] = 0; // Is active
    $data[]     = $userData;
}


$fp = fopen('php://output', 'w');

fputcsv($fp, ['title', 'first_name', 'last_name', 'structure_level', 'groups', 'comment', 'is_active'], ',', '"');

foreach ($data as $arr) {
    fputcsv($fp, $arr, ',', '"');
}
fclose($fp);